[platformio]
default_envs = esp32dev


[env:esp32dev]
platform = espressif32
board = esp32dev
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
framework = espidf
monitor_speed = 115200
build_type = release
build_flags =
    -std=gnu++17
    -fexceptions
    -DHK17_NETWORK_APP=1
build_src_filter =
    +<hk17_math.cpp>
    +<hk17_wire.cpp>
    +<network_main.cpp>


[env:conformance]
platform = espressif32
board = esp32dev
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
framework = espidf
monitor_speed = 115200
build_type = release
build_flags =
    -std=gnu++17
    -fexceptions
    -DHK17_CONFORMANCE_APP=1
build_src_filter =
    +<hk17_math.cpp>
    +<main.cpp>


[env:native]
platform = native
build_type = release
build_flags =
    -std=gnu++17
build_src_filter =
    +<hk17_math.cpp>
    +<main.cpp>
