[platformio]
default_envs = esp32dev


[env:esp32dev]
platform = espressif32
board = esp32dev
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
framework = espidf
monitor_speed = 115200
build_type = release
build_flags =
    -std=gnu++17
    -fexceptions
    -DHK17_NETWORK_APP=1


[env:conformance]
platform = espressif32
board = esp32dev
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
framework = espidf
monitor_speed = 115200
build_type = release
build_flags =
    -std=gnu++17
    -fexceptions
    -DHK17_CONFORMANCE_APP=1


[env:performance-smoke]
platform = espressif32
board = esp32dev
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
framework = espidf
monitor_speed = 115200
build_type = release
build_flags =
    -std=gnu++17
    -fexceptions
    -DHK17_PERFORMANCE_APP=1
    -DHK17_PERF_EXECUTIONS=5
    -DHK17_PERF_START_DELAY_MS=5000


[env:performance]
platform = espressif32
board = esp32dev
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
framework = espidf
monitor_speed = 115200
build_type = release
build_flags =
    -std=gnu++17
    -fexceptions
    -DHK17_PERFORMANCE_APP=1
    -DHK17_PERF_EXECUTIONS=1000
    -DHK17_PERF_START_DELAY_MS=5000


[env:native]
platform = native
build_type = release
build_flags =
    -std=gnu++17
build_src_filter =
    +<hk17_math.cpp>
    +<main.cpp>
