idf_component_register(
    SRCS
        "hk17_math.cpp"
        "hk17_wire.cpp"
        "main.cpp"
        "network_main.cpp"
        "performance_main.cpp"
    INCLUDE_DIRS
        "../include"
    REQUIRES
        esp_event
        esp_http_server
        esp_netif
        esp_timer
        esp_wifi
        mqtt
        nvs_flash
)
